<a href="https://colab.research.google.com/github/SajalDasShovon/ML-Approach/blob/main/Implementation_of_ANN_from_Scratch_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 # Importing Required Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras
from sklearn import datasets
data=datasets.load_iris()

In [ ]:
# Generating Random Dataset

#X = np.vstack([(np.random.rand(10, 2)*5), (np.random.rand(10, 2)*10)])
#Y = np.hstack([[0]*10, [1]*10])

#dataset = pd.DataFrame(X, columns={'X1', 'X2'})
#dataset['Y'] = Y

#dataset

data

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [ ]:
# Initiating Random Weights and Bias

# First Layer Weights and Bias
Wi_1 = np.random.rand(3, 2)
Bi_1 = np.random.rand(3)

# Second Layer Weights and Bias
Wi_2 = np.random.rand(3, 2)
Bi_2 = np.random.rand(2)

print('First Layer Weights: \n', Wi_1)
print('\nFirst Layer Biases: \n', Bi_1)

print('\nSecond Layer Weights: \n', Wi_2)
print('\nSecond Layer Weights: \n', Bi_2)

print('\nTranspose of Wi_1: \n', Wi_1.T)

First Layer Weights: 
 [[0.19356788 0.37825719]
 [0.03373174 0.05677415]
 [0.45189139 0.22605586]]

First Layer Biases: 
 [0.98033387 0.85154072 0.68540039]

Second Layer Weights: 
 [[0.33365647 0.10039533]
 [0.73995636 0.87714393]
 [0.66464993 0.23212312]]

Second Layer Weights: 
 [0.23778563 0.36844969]

Transpose of Wi_1: 
 [[0.19356788 0.03373174 0.45189139]
 [0.37825719 0.05677415 0.22605586]]


In [ ]:
# Defining the Forward Propagation Function

def forward_prop(X, Wi_1, Bi_1, Wi_2, Bi_2):
  # First Layer
  M = 1 / (1 + np.exp(-(X.dot(Wi_1.T) + Bi_1)))

  # Second Layer
  A = M.dot(Wi_2) + Bi_2
  expA = np.exp(A)
  
  Y = expA / expA.sum(axis=1, keepdims=True)

  return Y, M

In [ ]:
forward_prop(X, Wi_1, Bi_1, Wi_2, Bi_2)

In [ ]:
# Returns Gradient for Weight_2
#backword propagation
def diff_Wi_2(H, Z, Y):
  return H.T.dot(Z - Y)

# Returns Gradient for Weight_1
def diff_Wi_1(X, H, Z, output, Wi_2):
  dZ = (Z - output).dot(Wi_2.T) * H * (1 - H)
  
  return X.T.dot(dZ)

In [ ]:
# Returns Derivative for B2
def diff_B2(Z, Y):
  return (Z - Y).sum(axis=0)

# Returns Gradient for B1
def diff_B1(Z, Y, Wi_2, H):
  return ((Z - Y).dot(Wi_2.T) * H * (1 - H)).sum(axis=0)

In [ ]:
learning_rate = 1e-3

for epoch in range(5000):
  output, hidden = forward_prop(X, Wi_1, Bi_1, Wi_2, Bi_2)
  Wi_2 += learning_rate * diff_Wi_2(hidden, Z, output)
  Bi_2 += learning_rate * diff_B2(Z, output)
  Wi_1 += learning_rate * diff_Wi_1(X, hidden, Z, output, Wi_2).T
  Bi_1 += learning_rate * diff_B1(Z, output, Wi_2, hidden)

In [ ]:
X_test = np.array([1, 10])

hidden_output = 1 / (1 + np.exp(-X_test.dot(Wi_1.T) - Bi_1))
Outer_layer_output = hidden_output.dot(Wi_2) + Bi_2
expA = np.exp(Outer_layer_output)
Y = expA / expA.sum()

print('Prob of Class 0 >>> {} \n Prob of Class 1 >>> {}'.format(Y[0], Y[1]))